name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
    run:
      working-directory: ./build

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: DIRIT
      run: ls -R
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore PluginFramework.sln
    - name: Build
      run: dotnet build PluginFramework.sln --no-restore
    #- name: Test
      #run: dotnet test --no-build --verbosity normal
